from __future__ import annotations
from typing import cast

from pydantic import HttpUrl

from app.config.models import (
    AuditInfo,
    AudienceLevel,
    ConfigSource,
    ConfigStatus,
    ContentIntent,
    DiscoveryRule,
    DiscoveryStrategy,
    EntityExtractionPlan,
    EntityFieldPlan,
    EntityType,
    EntityValidationExpectation,
    ExtractStrategy,
    ExtractionStep,
    FetchConfig,
    FetchMode,
    KeywordExtractConfig,
    KeywordLabelGroup,
    LLMExtractConfig,
    MatchMode,
    PageConfig,
    PageType,
    PageValidationExpectation,
    PatternExtractConfig,
    PatternLabelGroup,
    PortalFamily,
    RecordLocator,
    RecordMatchStrategy,
    RequiredFieldExpectation,
    SelectorExtractConfig,
    TableExtractConfig,
    UniversityProfile,
    UniversityScraperConfig,
)

CONFIG = UniversityScraperConfig(
    profile=UniversityProfile(
        id="ug",
        university_name="University of Ghana",
        country="Ghana",
        root_domains=[
            "admissions.ug.edu.gh",
            "apply.ug.edu.gh",
            "www.ug.edu.gh",
        ],
        seed_urls=[
            cast(HttpUrl,"https://admissions.ug.edu.gh/"),
            cast(HttpUrl,"https://www.ug.edu.gh/"),
            cast(HttpUrl,"https://apply.ug.edu.gh/admissions/undergrad/login"),
            cast(HttpUrl,"https://apply.ug.edu.gh/admissions/iundergrad/login"),
            cast(HttpUrl,"https://apply.ug.edu.gh/admissions/graduate/login"),
            cast(HttpUrl,"https://apply.ug.edu.gh/admissions/igraduate/login"),
            cast(HttpUrl,"https://apply.ug.edu.gh/admissions/mature"),
        ],
        portal_family_hint=PortalFamily.CUSTOM_PHP,
        tags=["ghana", "multi-portal", "admissions"],
    ),
    audit=AuditInfo(
        source=ConfigSource.MANUAL,
        status=ConfigStatus.REVIEW_REQUIRED,
        confidence=0.82,
        version=1,
        notes=(
            "Real UG config based on public admissions pages and live portal login pages. "
            "Conservative version using mostly SINGLE_RECORD pages."
        ),
    ),
    discovery=[
        DiscoveryRule(
            name="ug-admissions-discovery",
            strategy=DiscoveryStrategy.MIXED,
            allowed_domains=[
                "admissions.ug.edu.gh",
                "apply.ug.edu.gh",
                "www.ug.edu.gh",
            ],
            include_url_patterns=[
                r"/admissions",
                r"/undergraduate",
                r"/graduate",
                r"/international",
                r"/entry-requirements",
                r"/how-to-apply",
                r"/deadlines",
                r"/mature",
            ],
            exclude_url_patterns=[
                r"/news",
                r"/events",
                r"/tag/",
                r"/wp-admin",
                r"/wp-content",
            ],
            include_anchor_text=[
                "admissions",
                "apply",
                "application",
                "deadlines",
                "entry requirements",
                "how to apply",
                "undergraduate",
                "graduate",
                "international",
                "mature",
            ],
            exclude_anchor_text=[
                "news",
                "event",
                "gallery",
            ],
            max_depth=2,
            max_pages=40,
        )
    ],
    pages=[
        PageConfig(
            name="ug_admissions_home",
            type=PageType.LANDING,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.GENERAL,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/"),
            canonical=True,
            priority=1,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Public admissions homepage with overview text and admission categories.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="university_from_homepage",
                    entity_type=EntityType.UNIVERSITY,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["name"],
                    fields=[
                        EntityFieldPlan(
                            field_name="name",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="site_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["title", "h1", ".site-title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="website_url",
                            steps=[
                                ExtractionStep(
                                    name="site_url_hint",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["body"],
                                        instruction=(
                                            "Extract the official main website URL of the university if it is stated "
                                            "or can be clearly inferred from the admissions page. Return null if absent."
                                        ),
                                        output_schema_name="scalar_url",
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="description",
                            steps=[
                                ExtractionStep(
                                    name="admissions_summary",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["main p", ".content p", "article p"]
                                    ),
                                )
                            ],
                        ),
                    ],
                ),
                EntityExtractionPlan(
                    name="admissions_home_portal_summary",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="home_portal_title",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="Undergraduate Admissions",
                                                keywords=["undergraduate admission"],
                                            ),
                                            KeywordLabelGroup(
                                                label="Graduate Admissions",
                                                keywords=["graduate admissions"],
                                            ),
                                        ],
                                        match_mode=MatchMode.CONTAINS,
                                    ),
                                ),
                                ExtractionStep(
                                    name="fallback_home_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2"]
                                    ),
                                ),
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="status",
                            steps=[
                                ExtractionStep(
                                    name="home_status_keyword",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="open",
                                                keywords=[
                                                    "applications are open",
                                                    "apply now",
                                                    "open for the admission",
                                                ],
                                            ),
                                            KeywordLabelGroup(
                                                label="closed",
                                                keywords=[
                                                    "applications closed",
                                                    "admissions closed",
                                                ],
                                            ),
                                            KeywordLabelGroup(
                                                label="upcoming",
                                                keywords=[
                                                    "coming soon",
                                                    "opens soon",
                                                ],
                                            ),
                                        ],
                                        match_mode=MatchMode.CONTAINS,
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="academic_year",
                            steps=[
                                ExtractionStep(
                                    name="year_pattern",
                                    strategy=ExtractStrategy.PATTERN,
                                    pattern_config=PatternExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            PatternLabelGroup(
                                                label="2025/2026",
                                                patterns=[r"2025\s*/\s*2026"],
                                            ),
                                            PatternLabelGroup(
                                                label="2026/2027",
                                                patterns=[r"2026\s*/\s*2027"],
                                            ),
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                ),
            ],
            validation=PageValidationExpectation(
                must_fetch=True,
                min_text_length=120,
                entities=[
                    EntityValidationExpectation(
                        entity_type=EntityType.UNIVERSITY,
                        min_records=1,
                        required_fields=[
                            RequiredFieldExpectation(field="name"),
                        ],
                    )
                ],
            ),
        ),
        PageConfig(
            name="ug_undergraduate_overview",
            type=PageType.CONTENT,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.UNDERGRADUATE,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/undergraduate/overview"),
            canonical=True,
            priority=2,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Public undergraduate admissions overview page.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="undergraduate_public_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="undergrad_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["undergraduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="status",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_status",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="open",
                                                keywords=["applications are open"],
                                            ),
                                            KeywordLabelGroup(
                                                label="closed",
                                                keywords=["applications closed"],
                                            ),
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="academic_year",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_year",
                                    strategy=ExtractStrategy.PATTERN,
                                    pattern_config=PatternExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            PatternLabelGroup(
                                                label="2025/2026",
                                                patterns=[r"2025\s*/\s*2026"],
                                            ),
                                            PatternLabelGroup(
                                                label="2026/2027",
                                                patterns=[r"2026\s*/\s*2027"],
                                            ),
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="instructions",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_guidance",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["main p", "article p", "li"]
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
            validation=PageValidationExpectation(
                must_fetch=True,
                min_text_length=100,
                entities=[
                    EntityValidationExpectation(
                        entity_type=EntityType.PORTAL,
                        min_records=1,
                        required_fields=[
                            RequiredFieldExpectation(field="title"),
                        ],
                    )
                ],
            ),
        ),
        PageConfig(
            name="ug_deadlines",
            type=PageType.TABLE,
            intent=ContentIntent.DEADLINES,
            audience=AudienceLevel.GENERAL,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/deadlines"),
            canonical=True,
            priority=3,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes=(
                "Structured deadlines page. Kept as SINGLE_RECORD for now because row-level "
                "record locator implementation may still be incomplete."
            ),
            entity_extractors=[
                EntityExtractionPlan(
                    name="deadlines_portal_summary",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="deadlines_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="instructions",
                            steps=[
                                ExtractionStep(
                                    name="deadlines_table_payload",
                                    strategy=ExtractStrategy.TABLE,
                                    table_config=TableExtractConfig(
                                        selectors=["table"],
                                        header_row_index=0,
                                        infer_headers=True,
                                    ),
                                ),
                                ExtractionStep(
                                    name="deadlines_llm_summary",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["body"],
                                        instruction=(
                                            "Summarize the admissions deadlines shown on this page in a compact text form. "
                                            "Include admission categories and their open/close status if visible."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                ),
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="opens_at",
                            steps=[
                                ExtractionStep(
                                    name="open_date_pattern",
                                    strategy=ExtractStrategy.PATTERN,
                                    pattern_config=PatternExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            PatternLabelGroup(
                                                label="13th March, 2025",
                                                patterns=[r"13th\s+March,\s+2025"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_undergraduate_entry_requirements",
            type=PageType.CONTENT,
            intent=ContentIntent.ENTRY_REQUIREMENTS,
            audience=AudienceLevel.UNDERGRADUATE,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/undergraduate/entry-requirements"),
            canonical=True,
            priority=4,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            entity_extractors=[
                EntityExtractionPlan(
                    name="undergraduate_requirements_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="requirements_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="requirements_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["undergraduate degree programme"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="requirements",
                            steps=[
                                ExtractionStep(
                                    name="requirements_text",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["main", "article", ".content"]
                                    ),
                                ),
                                ExtractionStep(
                                    name="requirements_llm_compact",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["main", "article", ".content", "body"],
                                        instruction=(
                                            "Extract a clean summary of the undergraduate entry requirements shown on the page. "
                                            "Focus on the general entry requirements only."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                ),
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_undergraduate_how_to_apply",
            type=PageType.CONTENT,
            intent=ContentIntent.HOW_TO_APPLY,
            audience=AudienceLevel.UNDERGRADUATE,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/undergraduate/how-to-apply"),
            canonical=True,
            priority=5,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            entity_extractors=[
                EntityExtractionPlan(
                    name="undergraduate_how_to_apply_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="how_to_apply_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="instructions",
                            steps=[
                                ExtractionStep(
                                    name="apply_steps_text",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["ol li", "ul li", "main p", "article p"]
                                    ),
                                ),
                                ExtractionStep(
                                    name="apply_steps_llm",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["main", "article", "body"],
                                        instruction=(
                                            "Extract the application instructions from this page as a concise plain-text summary."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                ),
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="fee_note",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_fee_note_llm",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["main", "article", "body"],
                                        instruction=(
                                            "Extract the application fee information from this page as a concise note, "
                                            "including voucher/payment information if present."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_graduate_how_to_apply",
            type=PageType.CONTENT,
            intent=ContentIntent.HOW_TO_APPLY,
            audience=AudienceLevel.GRADUATE,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/graduate-admissions/how-to-apply"),
            canonical=True,
            priority=6,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            entity_extractors=[
                EntityExtractionPlan(
                    name="graduate_how_to_apply_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="graduate_apply_title",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="Graduate Admissions",
                                                keywords=["ghanaian applicants", "all applications are done online"],
                                            )
                                        ],
                                        match_mode=MatchMode.CONTAINS,
                                    ),
                                ),
                                ExtractionStep(
                                    name="graduate_apply_title_fallback",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "title"]
                                    ),
                                ),
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="graduate_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="masters",
                                                keywords=["graduate", "postgraduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="instructions",
                            steps=[
                                ExtractionStep(
                                    name="graduate_apply_text",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["ol li", "ul li", "main p", "article p"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="fee_note",
                            steps=[
                                ExtractionStep(
                                    name="graduate_fee_note",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["main", "article", "body"],
                                        instruction=(
                                            "Extract the postgraduate application payment/voucher instructions from this page as a concise note."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_international_how_to_apply",
            type=PageType.CONTENT,
            intent=ContentIntent.HOW_TO_APPLY,
            audience=AudienceLevel.INTERNATIONAL,
            url=cast(HttpUrl,"https://admissions.ug.edu.gh/international/how-to-apply"),
            canonical=True,
            priority=7,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            entity_extractors=[
                EntityExtractionPlan(
                    name="international_how_to_apply_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="international_apply_title",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="International Undergraduate Applicants",
                                                keywords=["international", "ghanaians abroad undergraduate applicants"],
                                            )
                                        ],
                                        match_mode=MatchMode.CONTAINS,
                                    ),
                                ),
                                ExtractionStep(
                                    name="international_apply_title_fallback",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "title"]
                                    ),
                                ),
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="international_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["undergraduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="intl_fee_note",
                            steps=[
                                ExtractionStep(
                                    name="international_fee_note",
                                    strategy=ExtractStrategy.LLM,
                                    llm_config=LLMExtractConfig(
                                        selectors=["main", "article", "body"],
                                        instruction=(
                                            "Extract the international application fee information from this page as a concise note."
                                        ),
                                        output_schema_name="scalar_text",
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="instructions",
                            steps=[
                                ExtractionStep(
                                    name="international_apply_steps",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["ol li", "ul li", "main p", "article p"]
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_undergrad_ghanaian_login",
            type=PageType.LOGIN,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.UNDERGRADUATE,
            url=cast(HttpUrl,"https://apply.ug.edu.gh/admissions/undergrad/login"),
            canonical=True,
            priority=8,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Live UG undergraduate Ghanaian applicant login portal.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="undergrad_ghanaian_login_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="undergrad_login_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2", "h3", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="undergrad_login_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["undergraduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_undergrad_international_login",
            type=PageType.LOGIN,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.INTERNATIONAL,
            url=cast(HttpUrl,"https://apply.ug.edu.gh/admissions/iundergrad/login"),
            canonical=True,
            priority=9,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Live UG international undergraduate applicant login portal.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="undergrad_international_login_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="iundergrad_login_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2", "h3", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="iundergrad_login_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["undergraduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_graduate_ghanaian_login",
            type=PageType.LOGIN,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.GRADUATE,
            url=cast(HttpUrl,"https://apply.ug.edu.gh/admissions/graduate/login"),
            canonical=True,
            priority=10,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Live UG postgraduate Ghanaian applicant login portal.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="graduate_ghanaian_login_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="graduate_login_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2", "h3", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="graduate_login_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="masters",
                                                keywords=["postgraduate", "graduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_graduate_international_login",
            type=PageType.LOGIN,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.INTERNATIONAL,
            url=cast(HttpUrl,"https://apply.ug.edu.gh/admissions/igraduate/login"),
            canonical=True,
            priority=11,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Live UG postgraduate international applicant login portal.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="graduate_international_login_portal",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="igraduate_login_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2", "h3", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="igraduate_login_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="masters",
                                                keywords=["postgraduate", "graduate"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
        PageConfig(
            name="ug_mature_portal",
            type=PageType.LOGIN,
            intent=ContentIntent.ADMISSIONS,
            audience=AudienceLevel.UNDERGRADUATE,
            url=cast(HttpUrl,"https://apply.ug.edu.gh/admissions/mature"),
            canonical=True,
            priority=12,
            fetch=FetchConfig(mode=FetchMode.HTTP),
            notes="Live mature applicants portal.",
            entity_extractors=[
                EntityExtractionPlan(
                    name="mature_portal_login",
                    entity_type=EntityType.PORTAL,
                    many=False,
                    record_locator=RecordLocator(
                        strategy=RecordMatchStrategy.SINGLE_RECORD
                    ),
                    required_identity_fields=["title"],
                    fields=[
                        EntityFieldPlan(
                            field_name="title",
                            required=True,
                            steps=[
                                ExtractionStep(
                                    name="mature_login_title",
                                    strategy=ExtractStrategy.SELECTOR,
                                    selector_config=SelectorExtractConfig(
                                        selectors=["h1", "h2", "h3", "title"]
                                    ),
                                )
                            ],
                        ),
                        EntityFieldPlan(
                            field_name="degree_level",
                            steps=[
                                ExtractionStep(
                                    name="mature_login_degree",
                                    strategy=ExtractStrategy.KEYWORD,
                                    keyword_config=KeywordExtractConfig(
                                        selectors=["body"],
                                        labels=[
                                            KeywordLabelGroup(
                                                label="undergraduate",
                                                keywords=["mature applicants", "access course"],
                                            )
                                        ],
                                    ),
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
    ],
)